### ISSUE TITLE
Sito inesistente = crash

### ISSUE THREAD

**Issue by scaccomatto75** [CastagnaIT/Autorinomina#1]
Segnalo che, a causa della chiusura del sito e del dominio www.autorinomina.it, il programma va in crash e si chiude automaticamente.
L'unico modo affinché non avvenga é levare la spunta del controllo di nuove versioni (in Impostazioni).
Per evitare il crash e riuscire nell'intento, è necessario sconnettersi da Internet prima di avviare il programma.

Vista la permanente chiusura, proporrei di modificare i sorgenti affinché non sia più disponibile il controllo nuove versioni e che "informazioni su Autorinomina" punti al progetto su GitHub.

Infine, suggerirei di pubblicare comunque su GitHub anche l'ultima versione compilata per Windows e, in alternativa alla disattivazione del controllo nuove versioni, farlo puntare a cercare nuove versioni sul progetto su GitHub.

Maurizio G

**Comment by CastagnaIT** [comment]
Grazie per la segnalazione
vedrò di correggere il problema

**Comment by CastagnaIT** [comment]
se cortesemente puoi confermarmi che ora funziona procedo con la pubblicazione:
~[Autorinomina_v5.0.6.0_64bit_portable.zip]~
~[Autorinomina_v5.0.6.0_32bit_portable.zip]~

**Comment by scaccomatto75** [comment]
Grazie, ora funziona regolarmente.
